spring:
  application:
    name: mentorHub

  security:
    oauth2:
      client:
        registration:
          fayda:
            client-id: ${fayda.client-id}
            client-authentication-method: private_key_jwt
            authorization-grant-type: authorization_code
            redirect-uri: ${fayda.redirect-uri}
            scope: openid,profile,email
            client-secret: ${fayda.private-key-base64}  # ← client-secret here
            provider: fayda
        provider:
          fayda:
            authorization-uri: ${fayda.authorization-endpoint}
            token-uri: ${fayda.token-endpoint}
            user-info-uri: ${fayda.userinfo-endpoint}
fayda:
  client-id: crXYIYg2cJiNTaw5t-peoPzCRo-3JATNfBd5A86U8t0
  redirect-uri: http://localhost:8080/login/oauth2/code/fayda
  authorization-endpoint: https://esignet.ida.fayda.et/authorize
  token-endpoint: https://esignet.ida.fayda.et/v1/esignet/oauth/v2/token
  userinfo-endpoint: https://esignet.ida.fayda.et/v1/esignet/oidc/userinfo
  private-key-base64: MIIEvQIBADANBgkqhkiG9w0B...   # (your base64-encoded key here)
